server:
  port: 9010
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.234.128
aliyun:
  sms:
    accessKeyId: LTAI4FjQs6dsHcAk3nnR6obi
    accessKeySecret: JbtIrtWiRtHjJxqPJU3mKZuIj6HwBH
    template_code: SMS_176941971
    sign_name: 本地十次方社区项目